### PR TITLE
[travis] Override SWIFT_VERSION=4.0 on JOB=Xcode9 SWIFT_VERSION=4.0

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by norio-nomura** [comment]
confirmed that `-swift-version 4` was used on [travis's job](https://travis-ci.org/jpsim/Yams/jobs/258434075#L85).

**Comment by jpsim** [comment]
Doesn't the environment variable that's already set do the same thing?

**Comment by norio-nomura** [comment]
No.
[The build log](https://travis-ci.org/jpsim/Yams/jobs/258288660) of #49 does not contain `-swift-version 4`.

**Comment by norio-nomura** [comment]
I am sorry that my English is not good.
In order to override the build settings when running `xcodebuild`, we need to pass `SWIFT_VERSION=4.0` as a command line option. In #49 you can see from [the log](https://travis-ci.org/jpsim/Yams/jobs/258288660) that `-swift-version 3` is used.

**Comment by jpsim** [comment]
ok, thanks!

**Pull request merged**
