### PR TITLE
[Azure Pipelines] Add scheduled job

### PR DESCRIPTION
**Pull request by norio-nomura**
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers

### CODE REVIEW

**Comment by norio-nomura** [comment]
How do we know that the Nightly build has failed? 🤔

**Comment by jpsim** [comment]
Are these jobs passing right now?

> How do we know that the Nightly build has failed? 🤔

I think the author of the commit will get emailed.

**Comment by norio-nomura** [comment]
> Are these jobs passing right now?

Yes, on my local.
Hm, it may be better to make Nightly also work with ordinary PR.

**Comment by jpsim** [comment]
> Hm, it may be better to make Nightly also work with ordinary PR.

Why? That would encourage merging things that fail CI. I'd rather only merge green PRs, you?

**Comment by norio-nomura** [comment]
Even testing `norionomura/swift:nightly` seems overkill, so I'll commit changes `linux swift51` as scheduled job.

**Comment by norio-nomura** [comment]
Now, `linux swift51` job will triggered by both of PR and schedule.

**Comment by norio-nomura** [comment]
All jobs except `linux swift 51` are triggered by PR.

**Comment by norio-nomura** [comment]
> I think the author of the commit will get emailed.

Does this mean that I will not be notified if the commit you merged is the latest on the master?

**Comment by jpsim** [comment]
Yes, that's how I think it works. As long as one of us has the latest commit on master I think that should be fine.

**Comment by norio-nomura** [comment]
Ok, let's think again if the problem actually occurs. 👍

**Comment by norio-nomura** [comment]
I will check if the job actually started after one and a half hours.

**Comment by norio-nomura** [comment]
Even with the change of #189, the scheduled job did not work. 😞 
https://dev.azure.com/jpsim/Yams/_build?definitionId=2

I found following in [Q & A](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#my-build-didnt-run-what-happened):
> ### My build didn't run. What happened?
>
>Someone must view a page in your organization regularly for CI and scheduled builds to run. It can be any page, including, for example, **Azure Pipelines**.
>
>Your organization goes dormant five minutes after the last user signed out of Azure DevOps. After that, each of your build pipelines will run one more time. For example, while your organization is dormant:
>
> * A nightly build of code in your organization will run only one night until someone signs in again.
>
> * CI builds of an Other Git repo will stop running until someone signs in again.

Can this explain why schedule jobs do not work? 🤔

**Comment by jpsim** [comment]
I suppose that could explain it. If we really wanted to we could set up a bot that runs nightly tests. Not worth the effort IMO.

**Comment by norio-nomura** [comment]
According to the Developer Community post, editing yaml from the Azure GUI will make the schedule work. 😯
https://developercommunity.visualstudio.com/comments/623549/view.html

**Comment by norio-nomura** [comment]
confirmed that the scheduled job started to work.
https://dev.azure.com/jpsim/Yams/_build/results?buildId=785

**Comment by jpsim** [comment]
Lovely! When the 5.1 branch starts working again, we’ll know when it breaks more quickly.

**Pull request merged**
