### PR TITLE
[CircleCI] Change jazzy job to using docker

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by norio-nomura** [comment]
This change reduces the duration of  `jazzy` job from [2:03](https://circleci.com/gh/jpsim/Yams/1361) to [0:59](https://circleci.com/gh/jpsim/Yams/1372).
I expect this will be about 0:39, when docker's layer caching will works on all CircleCI's docker servers.

**Comment by jpsim** [comment]
How is jazzy installed on that Docker image? It looks like the job doesn’t use the checked in Gemfile?

**Comment by norio-nomura** [comment]
jazzy has been installed by `gem install jazzy`.
The image's Dockerfile and build log is following: https://hub.docker.com/r/norionomura/sourcekitten/builds/bpxsjafdsjura4rptfjnrmt/

**Comment by jpsim** [comment]
Can’t we keep the bundler installation instead?

**Comment by norio-nomura** [comment]
I think that we can. What is the advantage of installing with bundler?

**Comment by norio-nomura** [comment]
Hm, maybe I should make `norionomura/jazzy:0.9.3_swift-4.1.2` instead of `norionomura/sourcekitten:0.21.0_swift-4.1.2` for enabling pinning the version of jazzy. 🤔

**Comment by norio-nomura** [comment]
I have created [norionomura/jazzy](https://hub.docker.com/r/norionomura/jazzy/) and changed to use that with pinning jazzy version to 0.9.3 by image tag.

**Comment by jpsim** [comment]
Ok, but I don't think that was necessary, sorry for the delay in responding. My concern was that the version specified in Gemfile.lock didn't correspond to the version we're running on CI, which isn't actually resolved by pinning the Docker image to a jazzy version.

In any case, that's a small concern. I'm ok with either the `norionomura/jazzy` image or the one used before `norionomura/sourcekitten`. Up to you!

👍

**Comment by norio-nomura** [comment]
> My concern was that the version specified in Gemfile.lock didn't correspond to the version we're running on CI, which isn't actually resolved by pinning the Docker image to a jazzy version.

Thanks for explanation! 
:thinking: I'll try to use bundler with my docker image.

**Comment by norio-nomura** [comment]
I found another caching issues and opened #128 for fixing them.

**Comment by jpsim** [comment]
Presumably with #128 we don't need to use the jazzy docker image?

**Comment by norio-nomura** [comment]
The CircleCI's OSS plan supports parallel execution of Linux jobs, but does not support parallel execution of macOS jobs. So, I think that it is worth changing from macOS to docker.

**Comment by jpsim** [comment]
Oh yes, I'm still in favor of using Docker, I meant we don't need Jazzy pre-installed in a Docker image if we're installing it via Bundler. i.e. change `norionomura/jazzy:0.9.3_swift-4.1.2` to `norionomura/sourcekitten:swift-4.1.2`?

**Comment by norio-nomura** [comment]
Oh, I misunderstood.
I see. However, I have already deleted `norionomura/sourcekitten` from the docker hub and I think that contents will be the same as the jazzy image even if I make it again. So I want to proceed as it is.

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
