### PR TITLE
Fix and test string -> integer misstep upon decoding.

### PR DESCRIPTION
**Pull request by mattpolzin**
Fixes https://github.com/jpsim/Yams/issues/263 by only constructing integer and floating point values from scalars if those scalars are in the `plain` "flow" style. It additionally allows through scalars with no styling information (`any`).

### CODE REVIEW

**Comment by mattpolzin** [comment]
@jpsim apologies for the ping, but I'd love to get this fix applied (or officially declined). It's the only thing I currently know of that stops me from using Yams to ingest OpenAPI documentation in my a particular production application of OpenAPIKit.

**Comment by jpsim** [comment]
Looks great, thank you for the ping!

I just updated the changelog entry position to reflect that it's landing in master, will merge when CI passes.

Thanks for the PR.

**Comment by jpsim** [comment]
Do you need me to tag a release with this or can you point your use of Yams to master?

**Comment by mattpolzin** [comment]
I can point at master. Thank you!

**Pull request merged**
