### PR TITLE
Add unused imports CI job

### PR DESCRIPTION
**Pull request by jpsim**

### CODE REVIEW

**Comment by jpsim** [comment]
Making sure CI fails and that removing unused imports will make it pass.

**Comment by jpsim** [comment]
Unrelated, I never noticed how much faster UTF8 was than UTF16

image

**Comment by jpsim** [comment]
Also, it looks like Azure Pipelines is running automatically whenever I create or push commits to a PR. Maybe it's a permission issue that you need to manually trigger @norio-nomura ?

**Comment by norio-nomura** [comment]
> Maybe it's a permission issue that you need to manually trigger @norio-nomura ?

Sorry, I forgot to report. On working #146, I only needed the trigger manually once, CI was automatically started afterwards. 🙇

**Comment by norio-nomura** [comment]
> Unrelated, I never noticed how much faster UTF8 was than UTF16

The difference in processing time comes from whether it is compiled or not. `swift test with UTF8` job does not compile at all and only performs tests.
The actual speed difference due to encoding is not so much observable from the processing time of the whole test.

**Pull request merged**
