### PR TITLE
Use Multiline String Literals

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by norio-nomura** [comment]
Would it be unnecessary to test using `SWIFT_VERSION = 3.2`?

**Comment by norio-nomura** [comment]
Because there is no `swift-3.2-RELEASE` compiler, therefore "Swift>=3.2 is required" has the same meaning as "Swift>=4.0 is required".
In other words, if we do not support Swift 3.1.1, it seems pointless to say that we support Swift 3.2.

**Comment by jpsim** [comment]
Swift 3.2 is still a swift version, distinct from Swift 4.x, even if it's technically compiled using the same compiler as Swift 4.0.

**Comment by norio-nomura** [comment]
Hmm, I understand.

**Comment by norio-nomura** [comment]
Thanks for review! 🙏

**Pull request merged**
