### PR TITLE
Add Usage section to README.md

### PR DESCRIPTION
**Pull request by norio-nomura**
#73

### CODE REVIEW

**Comment by norio-nomura** [comment]
Should we test with CI that the sample code is buildable?

**Comment by jpsim** [comment]
It would be nice to have a high-level explanation of when to use `serialize` vs `dump` and `load` vs `compose`.

**Comment by norio-nomura** [comment]
Thanks for suggestion! Updated.

**Comment by jpsim** [comment]
> Should we test with CI that the sample code is buildable?

Nice to have, but not necessary for now.

I hope you don't mind, I made some edits. Let me know if you disagree with any of my changes.

Otherwise, feel free to merge this when you're happy with it! 👍

**Comment by norio-nomura** [comment]
I think that it became very good by your editing! Thanks! 🙏

**Pull request merged**
