### PR TITLE
Implement Emitter

### PR DESCRIPTION
**Pull request by norio-nomura**
This PR based on #14 and against to master.

Added:
- Serialize node functions:
  - `func serialize<Nodes>(nodes: Nodes, …) throws -> String where Nodes: Sequence, Nodes.Iterator.Element == Node`
  - `func serialize(node: Node, …) throws -> String`
- `Emitter` class

TODOs:
- [x] Fix `USE_UTF16`
- [x] Add style options to `Node`
- [x] Add dump object functions ~(another PR?)~:
  - `func dump<Objects>(objects: Objects, …) throws -> String where Objects: Sequence`
  - `func dump(object: Any?, …) throws -> String`
- ~[ ] Add tags support?~
- [x] Add more tests

### CODE REVIEW

**Comment by norio-nomura** [comment]
Maybe I should merge #17, #13 and #14 before reviewing this.

**Comment by norio-nomura** [comment]
The range assumed at the outset is almost complete..
There are still unfinished but I would like to implement them with another PR.
Could you please review this?
Thanks,

**Comment by jpsim** [comment]
All .travis.yml jobs pass locally. This is unbelievably good work @norio-nomura. I'm super impressed with how this turned out. I especially look forward to using the YAML emitter for programmatically generating sample SwiftLint configurations 😄

**Comment by norio-nomura** [comment]
Thanks for reviews and merging!
>  I especially look forward to using the YAML emitter for programmatically generating sample SwiftLint configurations 😄

Yeah, I intended to use them on that. 😉 
But there are still unfinished on styling nodes.
How do you think about adding tag as `0.2.0`? I have commits locally that update SourceKitten to using `Yams.compose()`, and tag is needed for SwiftPM.

**Comment by jpsim** [comment]
I've [tagged as 0.2.0](https://github.com/jpsim/Yams/releases/tag/0.2.0), [pushed to CocoaPods trunk](https://github.com/CocoaPods/Specs/commit/5a97f6da846e67048eb79a8eac65eafbb3f16c50) and filed a PR towards SourceKitten (https://github.com/jpsim/SourceKitten/pull/332).

I'd be very curious to see your changes to SourceKitten with `Yams.compose()` as it sounds like it could be better to use than my PR 😊.

By the way, I can give you push access to CocoaPods if you sign up. I tried earlier but it didn't find you:

```
$ pod trunk add-owner Yams norio.nomura@gmail.com
[!] No owner found with the specified email address.
```

**Comment by norio-nomura** [comment]
I just registered with CocoaPods. 😊

**Pull request merged**
