### PR TITLE
Use Swift 5.4 release toolchain on Windows

### PR DESCRIPTION
**Pull request by HeMet**
I think it should fix https://bugs.swift.org/browse/SR-13819 I tried it myself and all seems work https://github.com/HeMet/Yams/actions/runs/836795843

### CODE REVIEW

**Comment by jpsim** [comment]
Do all tests pass if you re-add the ones we disabled for Windows? Search for `TODO: Fix these tests on Windows` to see all the disabled tests.

**Comment by HeMet** [comment]
> Do all tests pass if you re-add the ones we disabled for Windows? Search for `TODO: Fix these tests on Windows` to see all the disabled tests.

No, these tests fails without any backtrace. The program just terminates silently.

In `testFloat` `sexagesimal` is causing crash. In `testInt` all cases are problematic. Since these tests testing basic stuff maybe this functionality is the source of all other failures.

**Comment by jpsim** [comment]
Right. I tried recently and filed https://bugs.swift.org/browse/SR-14513 to track the Windows crashes.

Nonetheless, it’ll be good to use an official release on CI rather than a snapshot.

**Comment by HeMet** [comment]
While processing sexagesimal number crash occurs here: https://github.com/jpsim/Yams/blob/main/Sources/Yams/Constructor.swift#L530 `String.sexagesimal` doesn't get called. It looks like a compiler bug.

**Pull request merged**
